-- 
-- Создание базы
--
CREATE DATABASE staff
CHARACTER SET utf8
COLLATE utf8_general_ci;
-- 
-- ПРАВА
-- 
CREATE USER 'userstaff'@'%' IDENTIFIED BY 'passwdstaff';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, GRANT OPTION, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE ON staff.* TO 'userstaff'@'%';
FLUSH PRIVILEGES;